### ISSUE TITLE
Upgrade from 1.16.0 to 1.24.x causes significant increase in query latency

### ISSUE THREAD

**Issue by urianawu** [pgbouncer/pgbouncer#1332]
Hi,

We currently deploy v1.16.0 pgbouncer and v1.17 cloud-sql-proxy on GKE(GCP k8 engine). This proxies all our async and sync workloads to our postgresql database in GCP. We have made multiple attempts to upgrade the pgbouncer to latest version but all resulted in rollback due to performance issue. I understand that performance issue is highly dependent on our specific setup so I will be as detailed as possible here. 

### bouncer
workloads are connecting to `bouncer` service of type Cluster IP, which is backed by 5 pods in us-east1.

Deployment YAML
```
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
      - env:
            - name: PGBOUNCER_MAX_CLIENT_CONN
              value: "15000"
            - name: PGBOUNCER_MAX_DB_CONNECTIONS
              value: "200"
            - name: PGBOUNCER_MAX_CLIENT_CONN
              value: '500'
            - name: PGBOUNCER_POOL_MODE
              value: transaction
            - name: PGBOUNCER_DEFAULT_POOL_SIZE
              value: '50'
            - name: PGBOUNCER_IGNORE_STARTUP_PARAMETERS
              value: extra_float_digits, statement_timeout
            - name: PGBOUNCER_EXTRA_FLAGS
              value: --quiet
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "4"
            memory: 4Gi
```

I've only attached relevant configs, other containers deployed on the pod include ` cloud-sql-proxy: gcr.io/cloudsql-docker/gce-proxy:1.17, pgbouncer-logs: cr.fluentbit.io/fluent/fluent-bit:2.2.2, pgbouncer-log-truncate: busybox:1.35, pgbouncer-exporter: prometheuscommunity/pgbouncer-exporter:v0.10.2 `

`pgbouncer.ini` on pod
```
[pgbouncer]
listen_port=6432
listen_addr=0.0.0.0
auth_file=/opt/bitnami/pgbouncer/conf/userlist.txt
auth_type=md5
pidfile=/opt/bitnami/pgbouncer/tmp/pgbouncer.pid
logfile=/opt/bitnami/pgbouncer/logs/pgbouncer.log
admin_users=redacted
client_tls_sslmode=disable
server_tls_sslmode=disable
pool_mode=transaction
max_client_conn=15000
max_db_connections=200
default_pool_size=200
ignore_startup_parameters=extra_float_digits, statement_timeout
```
### DB
Postgres config
```
 cloudsql.iam_authentication on
max_connections 2000
log_min_duration_statement 5000
max_worker_processes  10
max_wal_senders 10
log_lock_waits on
idle_in_transaction_session_timeout 120000
cloudsql.logical_decoding on
max_replication_slots  10
cloudsql.enable_pglogical on
```
We have one primary database with one read replica in us-east1.

### Client
[pg-promise 10.7.5](https://github.com/vitaly-t/pg-promise/tree/10.7.5)

### upgrade in place
When we updated pgbouncer image from `bitnami/pgbouncer:1.16.0` to `bitnami/pgbouncer:1.20.1` for existing deployment YAML, this immediately caused a near 100% app outage. In hind sight, this could have been due to ungraceful shutdown of v1.16.0 and could potentially stabilize after a while. But at the moment we rolled back to 1.16.0 to mitigate.

### migration to a new service with upgraded bouncer pods
We tried to be more cautious with our next attempts in upgrading, hence we followed these steps:
1. We setup a new Cluser IP service `new-bouncer`, with 10 pods running latest pgbouncer version 1.24.1.
2. Our workloads use Argo rollout, so we tuned the rollout to be a lot slower(maxSurge of 20%) trying to avoid a surge of connections to pgbouncer while workloads are getting switched over to call `new-bouncer` service.
3. We spread the load to `new-bouncer` so it has 10 pods and each pod has a lower max conn.
4. We monitored the `new-bouncer` pods during the switch over, periodically checking its connection to postgres.

This rollout was successful until 30mins post the switch. That's when we started seeing increased 5xx rate related to `query time out` in the app and rolled back to 1.16.0. We noticed that when bouncer was having performance issue we saw elevated server conn count, although as a sum across all pods it would still be under postgres max conn.

new bouncer deployment YAML:
```
  replicas: 10
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
      - env:
        - name: PGBOUNCER_MAX_CLIENT_CONN
          value: "7500"
        - name: PGBOUNCER_MAX_DB_CONNECTIONS
          value: "100"
        - name: PGBOUNCER_POOL_MODE
          value: transaction
        - name: PGBOUNCER_DEFAULT_POOL_SIZE
          value: "100"
        - name: PGBOUNCER_IGNORE_STARTUP_PARAMETERS
          value: extra_float_digits, statement_timeout
        - name: PGBOUNCER_CONNECT_QUERY
          value: SET statement_timeout=27000;
        - name: PGBOUNCER_LOG_FILE
          value: /opt/bitnami/pgbouncer/logs/pgbouncer.log
        image: bitnami/pgbouncer:1.24.1
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "2"
            memory: 4Gi
```
new bouncer `pgbouncer.ini` on pod:
```
[pgbouncer]
listen_port=6432
listen_addr=0.0.0.0
unix_socket_dir=/tmp/
unix_socket_mode=0777
auth_file=/opt/bitnami/pgbouncer/conf/userlist.txt
auth_type=scram-sha-256
pidfile=/opt/bitnami/pgbouncer/tmp/pgbouncer.pid
logfile=/opt/bitnami/pgbouncer/logs/pgbouncer.log
admin_users=redacted
client_tls_sslmode=disable
server_tls_sslmode=disable
pool_mode=transaction
max_client_conn=7500
max_db_connections=100
default_pool_size=100
ignore_startup_parameters=extra_float_digits, statement_timeout
stats_period=60
server_round_robin=0
server_fast_close=0
```

We'd really appreciate any leads or thoughts about what we missed!
