### ISSUE TITLE
closing because: client sent partial pkt in startup phase

### ISSUE THREAD

**Issue by spatialman** [pgbouncer/pgbouncer#490]
Hi, 

I am trying to host the pgbouncer linux container using "Azure - Web App Container" and trying connect to Azure PostgreSQL. During the startup i am getting below issues... Could someone through some light on this..
The below logs are getting emitted frequently:
LOG: closing because: client sent partial pkt in startup phase (age=0s)
WARNING: pooler error: client sent partial pkt in startup phase 

Because of this, container fails to start:

Initiating warmup request to container x for site y
Waiting for response to warmup request for container x. Elapsed time = 15.2121973 sec
Waiting for response to warmup request for container x. Elapsed time = 30.4317658 sec
..
..
Container x for site y did not start within expected time limit.
Stopping site y because it failed during startup

**Comment by edbergavera** [comment]
I am having the same issue with AKS. Have you figured out a solution to this?

**Comment by iBrooks** [comment]
I am also experiencing this issue, and only when deployed to Azure. The same container runs just fine locally, but on azure I get the following:

`LOG C-0x7fbcbbd17160: (nodb)/(nouser)@172.16.5.1:29265 closing because: client sent partial pkt in startup phase (age=0s)`
`WARNING C-0x7fbcbbd17160: (nodb)/(nouser)@172.16.5.1:29265 pooler error: client sent partial pkt in startup phase`

**Comment by eulerto** [comment]
This doesn't seem a pgbouncer issue. You should ask Azure why AKS or Web App Container is sending partial packets to Azure PostgreSQL. [Azure Database for PostgreSQL](https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/overview) provides a built-in pgbouncer. It is possibly a forked version that could explain this issue.

**Comment by michaelgmcd** [comment]
Seeing this as well when trying to use AWS Fargate connecting to RDS. Not sure how to proceed.

**Comment by Tieantono** [comment]
I guess this is because Azure App Service always pinging a HTTP request to the exposed port of your container, but since the exposed port of pgbouncer is not for HTTP request, the pgbouncer won't proceed and hence the Azure App Service think that your container didn't start well.

**Comment by Unintendedz** [comment]
I also got the same error while trying to connect to PgBouncer through Navicat via SSH. Initially, my setup in Docker Compose mapped PgBouncer's port to `127.0.0.1:15432:5432`, which caused the error. But when I changed the port mapping to `15432:5432`, bypassing SSH, the connection worked fine.

Below is my Docker Compose configuration:

```yaml
  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - web_gateway

  pgbouncer:
    image: edoburu/pgbouncer:1.22.0-p0
    environment:
      - DB_HOST=${POSTGRES_HOST}
      - DB_NAME=${POSTGRES_DB}
      - DB_PORT=${POSTGRES_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - AUTH_TYPE=scram-sha-256
      - POOL_MODE=transaction
    ports:
      - "127.0.0.1:15432:5432"
    depends_on:
      - postgres
    networks:
      - web_gateway
```
