### ISSUE TITLE
no such database postgres

### ISSUE THREAD

**Issue by zucatti** [pgbouncer/pgbouncer#795]
I have implemented a simple postgres 15 and a pgbouncer instance with this env :

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-pgbouncer
  name: {{ .Release.Name }}-pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pgbouncer
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pgbouncer
    spec:
      initContainers:
        # Wait for postgres to show up
        - name: check-db-ready
          image: postgres:latest
          command: ['sh', '-c', 
            'until pg_isready -h db -p 5432; 
            do echo waiting for database; sleep 2; done;']    
      containers:
      - env:
        - name: DB_HOST
          value: db
        - name: DB_PASSWORD
          value: {{ .Values.app.db.password }}
        - name: DB_USER
          value: postgres
        - name: POOL_MODE
          value: transaction
        - name: SERVER_RESET_QUERY
          value: DISCARD ALL
        - name: ADMIN_USERS
          value: postgres
        image: edoburu/pgbouncer:1.9.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - killall -INT pgbouncer && sleep 120
        name: pgbouncer
        ports:
          - containerPort: 5432
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
```
with db as postgres host. When I try to connect through pgbouncer, it ends with "no such database postgres"
